morse-bundle/morse-modeswitch-button: (APP-3771, PR #1029) be more resilient to slow hotplug
Defend against a slow hotplug meaning we never get the chance
to set our custom wifi defaults.

We want this order:
- hotplug -> wifi config -> /lib/wifi/morse.sh
- uci-defaults/30_uboot-envtools (so persistent_vars_storage.sh works)
- uci-defaults/98-morse-wireless-defaults

See /etc/init.d/boot for how this is triggered (kmodloader -> uci-defaults).

But because, well, it's a hotplug, it's hard to nicely know when it's
finished at boot time.

Really, I think OpenWrt should have a mechanism to easily hook into
the hotplug after the wifi-device/wifi-iface creation (e.g.  call a
uci-defaults style script with these two as arguments after each add,
or I guess one could attach a procd script for this). However, in
this case - though it would be easy to add - we would still have
the dependency on 30_uboot-envtools, so I've gone for the terrible
hack.


Approved-by: Evan Benn
Approved-by: Andrew Dodd
Approved-by: Lyall Beveridge

diff --git a/utils/morse-modeswitch-button/files/etc/uci-defaults/99-modeswitch b/utils/morse-modeswitch-button/files/etc/uci-defaults/99-modeswitch
--- a/utils/morse-modeswitch-button/files/etc/uci-defaults/99-modeswitch
+++ b/utils/morse-modeswitch-button/files/etc/uci-defaults/99-modeswitch
@@ -56,10 +56,16 @@ if [ "$mode" != sta ] && [ "$mode" != ap ]; then
 	exit 1
 fi
 
-echo "modeswitch: configuring as '$mode' (mm_mode)" > /dev/kmsg
-
 config_load wireless
 config_foreach _find_morse_device wifi-device
+if [ -z "$_morse_device_name" ]; then
+	# Note that 98-morse-wireless-defaults should already have done a sleep at this point.
+	echo "modeswitch: unable to find morse device to switch mode; reboot to retry" > /dev/kmsg
+	exit 1
+fi
+
+echo "modeswitch: configuring as '$mode' (mm_mode)" > /dev/kmsg
+
 uci set "wireless.default_$_morse_device_name.mode=$mode"
 
 if [ "$mode" = "sta" ]; then
